function out = GenRand2D(nsample)
out = randn(nsample, 2);
maxv = max(out);
angle = rand(1,1)*10*pi;
S = [rand(1,1)*10 0;0 rand(1,1)*10];
R = [cos(angle) -sin(angle);sin(angle) cos(angle)];
T = ones(nsample, 1)*[100*rand(1,1)*maxv(1) 100*rand(1,1)*maxv(2)];
out = out * S * R;
out = out - T;
